### ISSUE TITLE
Chance dropping resources on any campain and sandbox.

### ISSUE THREAD

**Issue by iGilga** [cech12/DigglesModManager#12]
Hi, in file `\Scripts\classes\zwerg\z_dignwalk.tcl` on `proc dig_execute`.
Have part code:
```
if {rand()<$rndval} {
 if {[im_in_campaign]} {
  set zone 0
  set UMK 0;set UTP 0; set UUM 0
  catch {set UMK [sm_get_event Uebergang_Met_Kris]}
  if {$UMK} {
   set zone 3
  } else {
   catch {set UTP [sm_get_event Titanic_Pumpe_aktiviert]}
   if {$UTP} {
    set zone 2
   } else {
    catch {set UUM [sm_get_event Uebergang_Urw_Met]}
    if {$UUM} {
     set zone 1
    }
   }
  }
 } else {
  global civ_state
  set zone [hmax 0 [hmin [expr {int($civ_state*10.0)}] 3]]
 }
 set mix [lindex {{0.0 1.1} {0.0 0.7 0.9 1.1} {0.0 0.5 0.66 0.94 1.1} {0.0 0.3 0.45 0.7 0.8 1.1}} $zone]
 set rnd [random]
 set idx -1
 foreach entry $mix {
  if {$rnd<$entry} {
   break
  } else {
   incr idx
  }
 }
 set cc [lindex {Stein Eisenerz Kohle Golderz Kristallerz} $idx]
 sel /obj
 set present [new $cc "" $digpoint {0 0 0}]
 set_physic $present true
 set_autolight $present false
 set_owner $present -1
}
```

I think need in game depends on event jump in other world. _No!_ Replace part code.
```
 if {[im_in_campaign]} {
  set zone 0
  set UMK 0;set UTP 0; set UUM 0
  catch {set UMK [sm_get_event Uebergang_Met_Kris]}
  if {$UMK} {
   set zone 3
  } else {
   catch {set UTP [sm_get_event Titanic_Pumpe_aktiviert]}
   if {$UTP} {
    set zone 2
   } else {
    catch {set UUM [sm_get_event Uebergang_Urw_Met]}
    if {$UUM} {
     set zone 1
    }
   }
  }
 } else {
  global civ_state
  set zone [hmax 0 [hmin [expr {int($civ_state*10.0)}] 3]]
 }
```
on new code
```  
 global civ_state
 set zone [hmax 0 [hmin [expr {int($civ_state*10.0)}] 3]]
```

Will any campain and solo nice dependes on level civilization.

**Comment by iGilga** [comment]
And row code chace dropping resources:
```set mix [lindex {{0.0 1.1} {0.0 0.7 0.9 1.1} {0.0 0.5 0.66 0.94 1.1} {0.0 0.3 0.45 0.7 0.8 1.1}} $zone]```

**Comment by cech12** [comment]
Hey iGilga,

I like that! :) 
So when I do this replacement, I will get the resources depending on my civilization level. That worked in solo before and after the replacement it works also in the campaign.
Is that correct?

**Comment by iGilga** [comment]
Hi, this change will work on sandbox and campain.

**Comment by cech12** [comment]
Ah okay,
I test the value of `[im_in_campaign]`. In campaign and sandbox it is `1` and in PvP it is `0.`
So this change edits the dropping resources in sandbox and campaign.

That is very interesting! :)
I can add a checkbox to the "ChangeGameSettings" mod, where you can switch this on and off. Is that okay? Or do you have a better idea?

**Comment by iGilga** [comment]
Okay.

**Comment by cech12** [comment]
No I will make a new mod "DroppingResources" where you can change the dropping chance, too.

**Comment by cech12** [comment]
Finished #13 :)
